rm("serverlogs", "serverlives", "lives", "updates", "majorupdates")
rm("dangerous", "cohorts", "cohortskills")
rm("summarygame", "summarygamekills", "summarygamegender")
rm("summaryowned", "summaryownedkills", "summaryownedgender")
rm("summaryplayed", "summaryplayedkills", "summaryplayedgender")
