rm("serverlogs", "serverlives", "alllives", "lives", "updates", "majorupdates")
rm("dangerous", "cohorts", "cohortskills")
rm("new_players", "summarynew")
rm("summarygame", "summarygamekills", "summarygamegender")
rm("summaryowned", "summaryownedkills", "summaryownedgender")
rm("summaryplayed", "summaryplayedkills", "summaryplayedgender")
rm("mainarea", "springs", "target", "eves", "sids", "bs2", "recent")
